### ISSUE TITLE
i know it is not working for now but any workaround

### ISSUE THREAD

**Issue by nakhla** [Mahyar24/findsub#2]
hii 
first, thank you for this piece of code, it was really useful.
second any workaround to overcome this limitation by subscene, i tried to use selenium and fetch the cookies associated with subscene and then send the request again with the url along with the fetched cookies but without lick and i still get 403 status code.
any ideas?

**Comment by Mahyar24** [comment]
Hi, 
You can try [CloudScraper](https://github.com/VeNoMouS/cloudscraper), as I did in the [0.7.2](https://github.com/Mahyar24/findsub/releases/tag/bypass_cloudflare_protection), but the problem didn't solve completely. Subscene is now in Cloudflare's harsh `Under Attack Mode`, making it impractical to scrape; you can bypass the `403` with the help of CloudScraper, but Cloudflare will count your requests, and when you want to download some subtitles or scrape pages concurrently It will throw a `429`. Rate-limiting is IP-based, and I can't think of an idea to bypass it.

So, sadly no.
